apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.gateway.mcp.io
spec:
  insecureSkipTLSVerify: true
  group: gateway.mcp.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: mcp-apiserver
    namespace: mcp-system
  version: v1

---

apiVersion: v1
kind: Service
metadata:
  namespace: mcp-system
  name: apiserver
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: mcp-apiserver
    apiserver: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mcp-system
  name: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-apiserver
      apiserver: "true"
  template:
    metadata:
      labels:
        app: mcp-apiserver
        apiserver: "true"
    spec:
      containers:
        - name: mcp-apiserver
          image: multicluster/mcp-apiserver:latest
          imagePullPolicy: Always
      serviceAccountName: mcp-manager
