apiVersion: v1
kind: Service
metadata:
  name: mcp-apiserver
  namespace: mcp-system
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mcp-apiserver
  namespace: mcp-system
subsets:
  - addresses:
      - ip: 127.0.0.1 # local host ip
    ports:
      - name: https
        port: 443
        protocol: TCP